@WebApi_HostAddress = http://localhost:5164

#Create
POST {{WebApi_HostAddress}}/documents
Content-Type: application/json; charset=UTF-8

{
    "id": "some-unique-identifier1",
    "tags": ["important", ".net"],
    "data": {
        "some": "data",
        "optional": "fields"
    }
}

###

#Create invalid
POST {{WebApi_HostAddress}}/documents
Content-Type: application/json; charset=UTF-8

{
    "id": "some-unique-identifier2",
    "tags": ["important", ".net"],
    "xdata": {
        "some": "data",
        "optional": "fields"
    }
}

###

#Update
PUT {{WebApi_HostAddress}}/documents
Content-Type: application/json; charset=UTF-8

{
    "id": "some-unique-identifier1",
    "tags": ["important", ".net", "cool"],
    "data": {
        "some": "data",
        "optional": "fields"
    }
}

###

#Get JSON
GET {{WebApi_HostAddress}}/documents/some-unique-identifier1
Accept: application/json

###

#Get MsgPack
GET {{WebApi_HostAddress}}/documents/some-unique-identifier1
Accept: application/x-msgpack

###

#Get XML
GET {{WebApi_HostAddress}}/documents/some-unique-identifier1
Accept: application/xml

###

#Not Found
GET {{WebApi_HostAddress}}/documents/xxx
Accept: application/json

###
